### ISSUE TITLE
The timer has stopped

### ISSUE THREAD

**Issue by Axel1117** [shinohara-rin/overcooked_all_dlc_patch#2]
In game, the timer dosen't move on from 4:00 minutes, but the DLCs patch works perfect

**Comment by shinohara-rin** [comment]
Which platform are you on? if I remembered correctly there's something wrong in the windows steam patch, I'll fix it once I get my PC.

**Comment by Axel1117** [comment]
Yeah, I'm on steam

**Comment by shinohara-rin** [comment]
I just uploaded a new one, can you please help me take a look if it works now?
https://github.com/shinohara-rin/overcooked_all_dlc_patch/blob/master/steam/windows/Assembly-CSharp.dll

**Comment by Axel1117** [comment]
Ok, I'll test it, thanks a lot

**Comment by Axel1117** [comment]
You fixed everything, thank you so much. Actually, another issue was some skins were already unlocked, so you fixed that also.
